#!/bin/bash

#

# skripti algus

read -p "Sisesta ridade arv: " rarv
read -p "Sisesta tarnide arv reas: " rida


for (( i = 1; i <= $rarv; i++ ))
do
	for (( j = 1 ; j <= $rida; j++ ))
	do
	   if [ $j -eq 1 ]; then
	       echo -n "$i. * "
	   else
	       echo -n "* "
	   fi
	done
      echo ""
done
