#!/bin/bash
# algarv v mitte 

# skripti algus

read -p "Sisesta suvaline arv: " arv


if [ $arv -le 1 ]
then
  echo "$arv - ei ole algarv"
else

  jagaja=2
  jaak=$((arv % jagaja))

  while [ $jaak -ne 0 ]
  do 
    jagaja=$((jagaja + 1))
    jaak=$((arv % jagaja))
  done

  if [ $arv -eq $jagaja ]
  then
    echo "$arv on algarv"
  else
    echo "$arv ei ole algarv"
  fi
fi

# skripti lopp
